# Generated by Django 6.1 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='leadership_role',
            field=models.CharField(blank=True, choices=[('peer_mentor', 'Peer Mentor'), ('tutor', 'Tutor'), ('house_committee', 'House Committee'), ('sub_warden', 'Sub Warden'), ('wellness_warrior', 'Wellness Warrior')], max_length=30),
        ),
    ]
