# Generated by Django 5.2.17 on 2026-08-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_and_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='leadership_role',
            field=models.CharField(blank=True, choices=[('peer_mentor', 'Peer Mentor'), ('tutor', 'Tutor'), ('house_committee', 'House Committee'), ('sub_warden', 'Sub Warden'), ('wellness_warrior', 'Wellness Warrior'), ('society_leader', 'Society Leader'), ('src', 'SRC Representative')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('student_leader', 'Student Leader')], default='student_leader', max_length=20),
        ),
    ]
