# Generated by Django 6.1 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('resources', '0002_booking')]
    operations = [migrations.AddField(model_name='booking', name='phone_number', field=models.CharField(default='', max_length=30), preserve_default=False)]
