# Generated by Django 5.2.17 on 2026-08-18 22:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['building', 'name']},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='type',
        ),
        migrations.AddField(
            model_name='resource',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='resource',
            name='manager_id',
            field=models.CharField(default='22222222-2222-2222-2222-222222222222', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='resource',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='venue_type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Classroom', 'Classroom'), ('Lecture Hall', 'Lecture Hall'), ('Auditorium', 'Auditorium'), ('Tutorial Room', 'Tutorial Room'), ('Event Venue', 'Event Venue'), ('Computer Lab', 'Computer Lab')], db_index=True, default='Classroom', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='venues',
        ),
        migrations.AddField(
            model_name='resource',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='resources.building'),
        ),
    ]
